
locale: "Tehran - Iran"
title: "Sara Azarnoush"
title_separator: "-"
description: "Computer Engineering Graduate from Sharif University of Technology | AI & ML | NLP & CV"
url: "https://saaz742.github.io"
baseurl: ""
repository: "saaz742/saaz742.github.io"

theme: "jekyll-theme-slate"
theme_color: "#1a1a2e"
highlight_color: "#ff6700"
font_family: "Inter, sans-serif"

author:
  avatar: "me.jpg"
  name: "Sara Azarnoush"
  pronouns: "she/her"
  bio: "I'm a Computer Engineering graduate from Sharif University of Technology, passionate about AI, ML, NLP, and Computer Vision. I develop intelligent systems and applies data science to real-world problems, while actively researching and building AI projects."
  location: "Tehran, Iran"
  email: "Sara.azarnoushh@gmail.com"

profiles:
  academic:
    arxiv: "https://arxiv.org/a/azarnoush_s.html"
    googlescholar: "https://scholar.google.com/citations?user=VqBL8YAAAAAJ&hl=en"
    semantic: "https://www.semanticscholar.org/author/Sara-Azarnoush/2165528162"
    orcid: "https://orcid.org/0000-0002-7435-0535"
    pubmed: "https://www.ncbi.nlm.nih.gov/myncbi/saaz"
    researchgate: "https://www.researchgate.net/profile/Sara-Azarnoush"

  dev:
    github: "https://github.com/saaz742"
    bitbucket: "https://bitbucket.org/saaz742"
    kaggle: "https://www.kaggle.com/saraazar"
    huggingface: "https://huggingface.co/Saaz742"
    codepen: "https://codepen.io/saaz742"

  creative:
    dribbble: "https://dribbble.com/sara-azarnoush"
    instagram: "https://instagram.com/saaz742"

  social:
    linkedin: "https://www.linkedin.com/in/sara-azarnoush"
    twitter: "https://twitter.com/AzarnoushSara"
    bluesky: "https://bsky.app/profile/saaz742.bsky.social"
    telegram: "https://t.me/saaz742"

  gaming:
    steam: "https://steamcommunity.com/id/saaz742"

teaser: ""
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC
