# =============================

# Sara Azarnoush - Personal AI / Professional Jekyll Site Config

# =============================

locale: "Tehran - Iran"
title: "Sara Azarnoush"
title_separator: "-"
name: &name "Sara Azarnoush"
description: &description "Computer Engineering Graduate from Sharif University of Technology, AI Enthusiast"
url: "[https://saaz742.github.io](https://saaz742.github.io)"
baseurl: ""
repository: "saaz742/saaz742.github.io"

theme_color: "#1a1a2e"
highlight_color: "#ff6700"
font_family: "Inter, sans-serif"

author:
avatar: "me.jpg"
name: "Sara Azarnoush"
pronouns: "she/her"
bio: "Sara Azarnoush is a Computer Engineering graduate from Sharif University of Technology, passionate about Machine Learning, NLP, Computer Vision, and AI-driven innovation. She builds intelligent systems, explores research frontiers, and develops products that merge data science with real-world applications. Currently working on AI projects and expanding her personal research and professional portfolio."
location: "Tehran, Iran"
email: "[Sara.azarnoushh@gmail.com](mailto:Sara.azarnoushh@gmail.com)"

author_profiles:
arxiv: "[https://arxiv.org/a/azarnoush_s.html](https://arxiv.org/a/azarnoush_s.html)"
googlescholar: "[https://scholar.google.com/citations?user=VqBL8YAAAAAJ&hl=en](https://scholar.google.com/citations?user=VqBL8YAAAAAJ&hl=en)"
orcid: "[https://orcid.org/0000-0002-7435-0535](https://orcid.org/0000-0002-7435-0535)"
semantic: "[https://www.semanticscholar.org/author/Sara-Azarnoush/2165528162](https://www.semanticscholar.org/author/Sara-Azarnoush/2165528162)"
pubmed: "[https://www.ncbi.nlm.nih.gov/myncbi/saaz@orcid](https://www.ncbi.nlm.nih.gov/myncbi/saaz@orcid)"
researchgate: "[https://www.researchgate.net/profile/Sara-Azarnoush](https://www.researchgate.net/profile/Sara-Azarnoush)"
scopus: ""

dev_profiles:
github: "[https://github.com/saaz742](https://github.com/saaz742)"
bitbucket: "[https://bitbucket.org/saaz742](https://bitbucket.org/saaz742)"
kaggle: "[https://www.kaggle.com/saraazar](https://www.kaggle.com/saraazar)"
huggingface: "[https://huggingface.co/Saaz742](https://huggingface.co/Saaz742)"
codepen: "[https://codepen.io/saaz742](https://codepen.io/saaz742)"

creative_profiles:
dribbble: "[https://dribbble.com/sara-azarnoush](https://dribbble.com/sara-azarnoush)"
instagram: "[https://instagram.com/saaz742](https://instagram.com/saaz742)"

social_profiles:
linkedin: "[https://www.linkedin.com/in/sara-azarnoush](https://www.linkedin.com/in/sara-azarnoush)"
twitter: "[https://twitter.com/AzarnoushSara](https://twitter.com/AzarnoushSara)"
bluesky: "[https://bsky.app/profile/saaz742.bsky.social](https://bsky.app/profile/saaz742.bsky.social)"
telegram: "[https://t.me/saaz742](https://t.me/saaz742)"

gaming_profiles:
steam: "[https://steamcommunity.com/id/saaz742](https://steamcommunity.com/id/saaz742)"

publication_category:
books:
title: "Books"
manuscripts:
title: "Journal Articles"
conferences:
title: "Conference Papers"

teaser: ""
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
provider: false

atom_feed:
hide: false
path: ""

social:
type: "Person"
name: "Sara Azarnoush"
links:
- name: "LinkedIn"
url: "[https://www.linkedin.com/in/sara-azarnoush](https://www.linkedin.com/in/sara-azarnoush)"
- name: "GitHub"
url: "[https://github.com/saaz742](https://github.com/saaz742)"
- name: "Twitter"
url: "[https://twitter.com/AzarnoushSara](https://twitter.com/AzarnoushSara)"
- name: "Telegram"
url: "[https://t.me/saaz742](https://t.me/saaz742)"
- name: "Instagram"
url: "[https://instagram.com/saaz742](https://instagram.com/saaz742)"
- name: "Kaggle"
url: "[https://www.kaggle.com/saraazar](https://www.kaggle.com/saraazar)"
- name: "HuggingFace"
url: "[https://huggingface.co/Saaz742](https://huggingface.co/Saaz742)"
- name: "ResearchGate"
url: "[https://www.researchgate.net/profile/Sara-Azarnoush](https://www.researchgate.net/profile/Sara-Azarnoush)"
- name: "arXiv"
url: "[https://arxiv.org/a/azarnoush_s.html](https://arxiv.org/a/azarnoush_s.html)"
- name: "ORCID"
url: "[https://orcid.org/0000-0002-7435-0535](https://orcid.org/0000-0002-7435-0535)"
- name: "Semantic Scholar"
url: "[https://www.semanticscholar.org/author/Sara-Azarnoush/2165528162](https://www.semanticscholar.org/author/Sara-Azarnoush/2165528162)"

analytics:
provider: false
google:
tracking_id: ""

include:

* .htaccess
* _pages
* files
  exclude:
* "*.sublime-project"
* "*.sublime-workspace"
* .asset-cache
* .bundle
* .github
* .jekyll-assets-cache
* .sass-cache
* assets/js/_main.js
* assets/js/plugins
* assets/js/vendor
* CHANGELOG
* Capfile
* config
* Dockerfile
* Gemfile
* Gruntfile.js
* gulpfile.js
* LICENSE
* local
* log
* node_modules
* package.json*
* Rakefile
* README
* tmp
* vendor
  keep_files:
* .git
* .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
input: GFM
hard_wrap: false
auto_ids: true
footnote_nr: 1
entity_output: as_char
toc_levels: 1..6
smart_quotes: lsquo,rsquo,ldquo,rdquo
enable_coderay: false

defaults:

* scope:
  path: ""
  type: pages
  values:
  layout: single
  author_profile: true

sass:
sass_dir: _sass
style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:

* jekyll-feed
* jekyll-gist
* jekyll-paginate
* jekyll-sitemap
* jekyll-redirect-from
* jemoji

category_archive:
type: liquid
path: /categories/
tag_archive:
type: liquid
path: /tags/

compress_html:
clippings: all
ignore:
envs: development
